architecture: YOLOv3
use_gpu: true
max_iters: 220000
log_iter: 100
save_dir: output
snapshot_iter: 1000
metric: COCO
pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/MobileNetV2_ssld_pretrained.tar
weights: output/yolov3_mobilenet_v2_coco/model_final
num_classes: 80
use_fine_grained_loss: false

YOLOv3:
  backbone: MobileNetV2
  yolo_head: YOLOLiteHead

MobileNetV2:
  norm_type: sync_bn
  scale: 1.0

YOLOLiteHead:
  anchor_masks: [[3, 4, 5], [0, 1, 2]]
  anchors: [[20, 37], [49, 94], [73, 201],
            [143, 265], [153, 121], [280, 279]]
  downsample: [32, 16]
  act: 'relu6'
  yolo_loss: YOLOv3Loss
  nms:
    background_label: -1
    keep_top_k: 100
    nms_threshold: 0.45
    nms_top_k: 1000
    normalized: false
    score_threshold: 0.01

YOLOv3Loss:
  ignore_thresh: 0.7
  label_smooth: false

LearningRate:
  base_lr: 0.0005
  schedulers:
  - !PiecewiseDecay
    gamma: 0.2
    milestones:
    - 170000
    - 195000

OptimizerBuilder:
  optimizer:
    momentum: 0.0
    type: RMSPropOptimizer
  regularizer:
    factor: 0.000004
    type: L2


TrainReader:
  inputs_def:
    fields: ['image', 'gt_bbox', 'gt_class', 'gt_score']
    num_max_boxes: 50
  dataset:
    !COCODataSet
      image_dir: train2017
      anno_path: annotations/instances_train2017.json
      dataset_dir: dataset/coco
      with_background: false
  sample_transforms:
    - !DecodeImage
      to_rgb: True
      with_mixup: True
    - !MixupImage
      alpha: 1.5
      beta: 1.5
    - !ColorDistort {}
    - !RandomExpand
      fill_value: [127.5, 127.5, 127.5]
    - !RandomCrop {}
    - !RandomFlipImage
      is_normalized: false
    - !NormalizeBox {}
    - !PadBox
      num_max_boxes: 50
    - !BboxXYXY2XYWH {}
  batch_transforms:
  - !RandomShape
    sizes: [288, 320, 352, 384, 416]
    random_inter: True
  - !NormalizeImage
    mean: [127.5, 127.5, 127.5]
    std: [127.5, 127.5, 127.5]
    is_scale: false
    is_channel_first: false
  - !Permute
    to_bgr: false
    channel_first: True
  # Gt2YoloTarget is only used when use_fine_grained_loss set as true,
  # this operator will be deleted automatically if use_fine_grained_loss
  # is set as false
  - !Gt2YoloTarget
    anchor_masks: [[3, 4, 5], [0, 1, 2]]
    anchors: [[20, 37], [49, 94], [73, 201],
            [143, 265], [153, 121], [280, 279]]
    downsample_ratios: [32, 16]
  batch_size: 32
  mixup_epoch: 52
  shuffle: true
  drop_last: true
  worker_num: 8
  bufsize: 16
  use_process: true


EvalReader:
  inputs_def:
    fields: ['image', 'im_size', 'im_id']
    num_max_boxes: 50
  dataset:
    !COCODataSet
      image_dir: val2017
      anno_path: annotations/instances_val2017.json
      dataset_dir: dataset/coco
      with_background: false
  sample_transforms:
    - !DecodeImage
      to_rgb: True
    - !ResizeImage
      target_size: 352
      interp: 2
    - !NormalizeImage
      mean: [127.5, 127.5, 127.5]
      std: [127.5, 127.5, 127.5]
      is_scale: false
      is_channel_first: false
    - !PadBox
      num_max_boxes: 50
    - !Permute
      to_bgr: false
      channel_first: True
  batch_size: 8
  drop_empty: false
  worker_num: 8
  bufsize: 16

TestReader:
  inputs_def:
    image_shape: [3, 352, 352]
    fields: ['image', 'im_size', 'im_id']
  dataset:
    !ImageFolder
      anno_path: annotations/instances_val2017.json
      with_background: false
  sample_transforms:
    - !DecodeImage
      to_rgb: True
    - !ResizeImage
      target_size: 352
      interp: 2
    - !NormalizeImage
      mean: [127.5, 127.5, 127.5]
      std: [127.5, 127.5, 127.5]
      is_scale: false
      is_channel_first: false
    - !Permute
      to_bgr: false
      channel_first: True
  batch_size: 1
